cache:
  directories:
    - $HOME/node_modules

deploy:
  on:
    branch: master
    node: "6"
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true

language: node_js

node_js: "6"

notifications:
  email: false

matrix:
  include:
    - node_js: "4"
      script: "yarn run feature-test -- --profile node-4"
    - node_js: "0.12"
      script: "yarn run feature-test -- --profile node-0.12"

sudo: false
