rvm: "1.9.2"
before_script: "git submodule update --init && npm install"
script: "rake"

node_js:
  - 0.6
  - 0.8

branches:
  only:
    - master

notifications:
  email:
    - jb@jbpros.com
  irc:
    - "irc.freenode.org#cucumber"
