cache:
  directories:
    - $HOME/node_modules

language: node_js

node_js:
  - "6"
  - "5"
  - "4"
  - "iojs"

matrix:
  include:
    - node_js: "0.12"
      script: "npm run test-es5"
    - node_js: "0.10"
      script: "npm run test-es5"

sudo: false

deploy:
  on:
    branch: master
    node: "5"
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
