cache:
  directories:
    - $HOME/node_modules

deploy:
  - on:
      node: "6"
      tags: true
    provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
  - api_key: "$NPM_AUTH_TOKEN"
    email: "charles.w.rudolph@gmail.com"
    on:
      node: "6"
      tags: true
    provider: npm
    skip_cleanup: true

language: node_js

node_js: "6"

notifications:
  email: false

matrix:
  include:
    - node_js: "7"
    - node_js: "4"
      script: "yarn run feature-test -- --profile node-4"

sudo: false
