name: Release NPM (latest)

on:
  push:
    branches: ["dev"]

permissions:
  contents: write    

jobs:
  publish-npm:
    name: Publish NPM module
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install-test

      - name: Configure git
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME}}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          

      - name: Fetch current version from npm with tag 'next'
        id: npm_version
        run: |
            version=$(npm show @dev-blinq/cucumber-js@next version)
            echo "version=$version" >> $GITHUB_ENV

      - name: Increment version
        id: increment-version
        run: |
          current_version=${{ env.version }}
          IFS='.' read -r -a version_parts <<< "$current_version"
          preid="dev"
          patch_version=$((version_parts[2]+1))
          NEW_VERSION="${version_parts[0]}.${version_parts[1]}.${patch_version}-${preid}"

          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
              
      - name: Update package.json with new npm version
        run: |
              jq --arg new_version "${{ env.new_version }}" '.version = $new_version' "${{ github.workspace }}/package.json" > "${{ github.workspace }}/package.json.tmp" && mv "${{ github.workspace }}/package.json.tmp" "${{ github.workspace }}/package.json"


      - name: Update package-lock.json
        run: npm install --package-lock-only
        working-directory: ${{ github.workspace }}      

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB}}
        run: |
          git add ${{ github.workspace }}/package.json ${{ github.workspace }}/package-lock.json
          git commit -m "new version commited"
          git push origin dev     

      
      - uses: cucumber/action-publish-npm@v1.1.0
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          npm-tag: 'next'
